server:
  port: 83


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 修改服务注册中的命名空间 默认是注册到public
        namespace: b631b99f-48e7-47e7-9768-709f27bbf914
        # 修改服务注册到nacos上分组名称，默认是DEFAULT_GROUP
        group: miaosha

service-url:
  nacos-user-service: http://nacos-payment-provider
  nacos-store-service: http://nacos-store-provider